CREATE TABLE t_people(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT '人员全局ID',
name VARCHAR(255) NOT NULL COMMENT '人员姓名',
idcard VARCHAR(255) NOT NULL COMMENT '身份证',
region BIGINT(20) NOT NULL COMMENT '区域(省市区)',
household VARCHAR(255) COMMENT '户籍',
address VARCHAR(255) COMMENT '现居地',
sex INT(2) DEFAULT 0 COMMENT '性别',
age INT(2) COMMENT '年龄',
birthday DATE COMMENT '出生日期',
politic INT(2) COMMENT '政治面貌',
edulevel INT(2) COMMENT '文化程度',
job VARCHAR(255) COMMENT '职业',
birthplace VARCHAR(255) COMMENT '籍贯',
community BIGINT(20) COMMENT '小区',
flag BIGINT(20) COMMENT'标签',
idcardpic BIGINT(20) COMMENT '证件照片',
capturepic BIGINT(20) COMMENT '实际采集照片',
imsi BIGINT(20) COMMENT 'IMSI码',
phone BIGINT(20) COMMENT '联系方式',
house BIGINT(20) COMMENT '房产信息',
car BIGINT(20) COMMENT '车辆信息',
createtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
updatetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
UNIQUE KEY (id),
UNIQUE KEY (idcard)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '人口库';


CREATE TABLE t_flag(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT 'ID',
flagid BIGINT(20) NOT NULL COMMENT '标签ID',
flag int(2) NOT NULL COMMENT '标签',
UNIQUE KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '标签表';


CREATE TABLE t_picture(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT 'ID',
peopleid BIGINT(20) NOT NULL COMMENT '人员全局ID',
idcardpicid BIGINT(20) COMMENT '证件照片ID',
idcardpic LONGBLOB COMMENT '证件照片',
capturepicid BIGINT(20) COMMENT '实际采集照片ID',
capturepic LONGBLOB COMMENT '实际采集照片',
feature VARCHAR(8192) NOT NULL COMMENT '特征值',
bitfeature VARCHAR(512) NOT NULL COMMENT 'bit特征值',
UNIQUE KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '照片信息库';


CREATE TABLE t_imsi(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT 'ID',
imsiid BIGINT(20) NOT NULL COMMENT 'IMSI码ID',
imsi VARCHAR(255) NOT NULL COMMENT 'IMSI码',
UNIQUE KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'IMSI码表';


CREATE TABLE t_phone(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT 'ID',
phoneid BIGINT(20) NOT NULL COMMENT '联系方式ID',
phone VARCHAR(255) NOT NULL COMMENT '联系方式',
UNIQUE KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '联系方式表';


CREATE TABLE t_house(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT 'ID',
houseid BIGINT(20) NOT NULL COMMENT '房产信息ID',
house VARCHAR(255) NOT NULL COMMENT '房产信息',
UNIQUE KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '房产信息表';


CREATE TABLE t_car(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT 'ID',
carid BIGINT(20) NOT NULL COMMENT '车辆信息ID',
car VARCHAR(255) NOT NULL COMMENT '车辆信息',
UNIQUE KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '车辆信息表';