version: '2.3'

services:
  haproxy-ftp:
    image: registry.cn-hangzhou.aliyuncs.com/hzgc/haproxy-ftp:1.0
    container_name: haproxy-ftp
    restart: always
    network_mode: "host"
    environment:
    - FTP_OPTION=ftp1:${DOCKER_HOST_IP}:2131, ftp2:${DOCKER_HOST_IP}:2132, ftp3:${DOCKER_HOST_IP}:2133
    ports:
    - "2121:2121"
    - "2123:2123"

  ftp-proxy:
    image: ${DOCKER_REPOSITOR}/hzgc/collect-ftp:${COLLECT_FTP_VERSION}
    container_name: ftp-proxy
    restart: always
    runtime: nvidia
    network_mode: "host"
    environment:
    - PROFILES_ACTIVE=proxy
    - ZOOKEEPER_HOST=${ZK_HOST}:${ZK_PORT}
    - HOST_IP=${DOCKER_HOST_IP}
    - HOST_NAME=${DOCKER_HOST_NAME}
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - SEEMMO_URL=http://${SEEMO_URL}:7000/ImgProcService/Recognize
    volumes:
    - ${FTP_HOME}:${FTP_HOME}

  ftp1:
    image: ${DOCKER_REPOSITOR}/hzgc/collect-ftp:${COLLECT_FTP_VERSION}
    container_name: ftp1
    restart: always
    runtime: nvidia
    network_mode: "host"
    environment:
    - PROFILES_ACTIVE=ftp
    - HOST_IP=${DOCKER_HOST_IP}
    - HOST_NAME=${DOCKER_HOST_NAME}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - SEEMMO_URL=http://${SEEMO_URL}:7000/ImgProcService/Recognize
    - HOME_DIR=${FTP_HOME}
    - FTP_PORT=2131
    volumes:
    - ${FTP_HOME}:${FTP_HOME}

  ftp2:
    image: ${DOCKER_REPOSITOR}/hzgc/collect-ftp:${COLLECT_FTP_VERSION}
    container_name: ftp2
    restart: always
    runtime: nvidia
    network_mode: "host"
    environment:
    - PROFILES_ACTIVE=ftp
    - HOST_IP=${DOCKER_HOST_IP}
    - HOST_NAME=${DOCKER_HOST_NAME}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - SEEMMO_URL=http://${SEEMO_URL}:7000/ImgProcService/Recognize
    - HOME_DIR=${FTP_HOME}
    - FTP_PORT=2132
    volumes:
    - ${FTP_HOME}:${FTP_HOME}

  ftp3:
    image: ${DOCKER_REPOSITOR}/hzgc/collect-ftp:${COLLECT_FTP_VERSION}
    container_name: ftp3
    restart: always
    runtime: nvidia
    network_mode: "host"
    environment:
    - PROFILES_ACTIVE=ftp
    - HOST_IP=${DOCKER_HOST_IP}
    - HOST_NAME=${DOCKER_HOST_NAME}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - SEEMMO_URL=http://${SEEMO_URL}:7000/ImgProcService/Recognize
    - HOME_DIR=${FTP_HOME}
    - FTP_PORT=2133
    volumes:
    - ${FTP_HOME}:${FTP_HOME}

  ftpmonitor:
    image: ${DOCKER_REPOSITOR}/hzgc/ftpmonitor:${VERSION}
    container_name: ftpmonitor
    restart: always
    environment:
    - ZK_ADDRESS=${ZK_HOST}:${ZK_PORT}
    - ES_HOST=${ES_HOST}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    network_mode: "host"
    volumes:
    - ${DOCKER_HOME}/ftpmonitor/log:/monitor/logging


