version: '2.3'

services:
  dispatch-background:
    image: ${DOCKER_REPOSITOR}/hzgc/dispatch-background:${DISPATCH_BACKGROUND_VERSION}
    container_name: dispatch-background
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/GsFaceLib/face_libs
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    extra_hosts:
    - platform:${PLATFORM_HOST}
    volumes:
    - /opt/GsFaceLib:/opt/GsFaceLib


  dispatch:
    image: ${DOCKER_REPOSITOR}/hzgc/dispatch:${DISPATCH_VERSION}
    container_name: dispatch
    network_mode: "host"
    environment:
    - EUREKA_IP=${EUREKA_HOST_IP}
    - EUREKA_PORT=${EUREKA_HOST_PORT}
    - MYSQL_HOST=${MYSQL_HOST}:${MYSQL_PORT}
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - KAFKA_HOST=${KAFKA_HOST}:${KAFKA_PORT}
    extra_hosts:
    - platform:${PLATFORM_HOST}